import type { Metadata } from "next";
import { Momo_Trust_Display, Archivo } from "next/font/google";
import "./globals.css";

const archivo = Archivo({
  subsets: ["latin", "vietnamese"],
  variable: "--font-archivo",
  display: "swap",
});

const momoTrust = Momo_Trust_Display({
  subsets: ["latin", "vietnamese"],
  weight: ["400"],   // lấy các weight bạn cần
  variable: "--font-momo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi" className={`${archivo.variable} ${momoTrust.variable}`}>
      <body>{children}</body>
    </html>
  );
}
